version: '2.2'

services:

  redis-master:
    image: "com.max.redis-master:6.0"
    hostname: redis-master
    ports:
      - '6379:6379'
    volumes:
      - "./certs:/certs"
    networks:
      default:
        aliases:
          - redis-master

  redis-slave:
    image: "com.max.redis-slave:6.0"
    hostname: redis-slave
    ports:
      - '6380-6381:6379'
    volumes:
      - "./certs:/certs"
    networks:
      default:
        aliases:
          - redis-slave

  redis-sentinel:
    image: "com.max.redis-sentinel:6.0"
    ports:
      - '26379-26381:26379' # TLS port
    volumes:
      - "./certs:/certs"
    networks:
      default:
        aliases:
          - redis-sentinel

networks:
  default:
    external:
      name: my-redis-network
